### ISSUE TITLE
Build Polkassenbly front-server

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#118]
Not sure how to do this with prisma but I guess we can have something like an admin password and use this in node-watcher.

Right now anyone can change anything in the DB by just ~~knowing the IP~~ edit: accessing it from the same cluster.

**Comment by yjkimjunior** [comment]
the cloudsql instance for the chain db has an admin user and password whose credentials are stored as a k8s pod secret.

**Comment by Tbaut** [comment]
But because it's in the same cloud instance, our hasura stitching server can update/delete/insert anything. We can't secure that from hasura's end (yet, that's a feature in progress).

**Comment by yjkimjunior** [comment]
ah yeah, that's true, still not anyone can write anything by just knowing the IP, they'd need to write from either a nomidot server or a polkassembly server, so probably the biggest concern is us shooting ourselves in the foot. I guess we could give our servers their own service account with a viewer role for the db and then you'd only be able to read even if the server is compromised

**Comment by Tbaut** [comment]
But Nomidot will speak to the graphql server (that will speak to the DB with credentials) isn't it?
Well, because Nomidot is accessible from the outside, we can actually use any query as long as there's no restriction put in place.

> I guess we could give our servers their own service account with a viewer role for the db and then you'd only be able to read even if the server is compromised

The thing is that we don't talk to the DB (at least I don't), we talk to prisma/graphql server, that has all the rights. So I guess we need to see how to restrict the access to some queries.

**Comment by yjkimjunior** [comment]
> But Nomidot will speak to the graphql server (that will speak to the DB with credentials) isn't it?

yes, but that doesn't make it "accessible from the outside" (if I'm understanding you correctly). Nomidot and its microservices are only accessible from within the same cluster. The DB exists separately outside of the cluster, which is why we need to use the proxy to create a secure connection.

The only attack vector I could see is if someone were to be able to ssh into a running prisma server container and then try to write from there. But at that point that means they've got a hold of our GCP credentials anyway.

Beyond the frontend being accessible from the outside, the only thing we need to enforce is that no servers have resolvers to write anything to chain db in the first place. We can add IAM roles to more strictly enforce that.

> So I guess we need to see how to restrict the access to some queries.

I'm thinking Queries (Reads), all access. Writes, zero access. All servers connecting to chaindb will have read-only permissions. Only the nodewatcher gets to write.

**Comment by Tbaut** [comment]
renamed it. What we need to do is what's been done here for Nomidot queries and subscriptions https://github.com/paritytech/Nomidot/pull/138/files
